services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes: # <--- 이 부분 추가!
      - ./influxdb-data:/var/lib/influxdb
    networks:
      - k6-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000" # 로컬 3000포트가 프론트엔드와 겹칠 수 있어 3001로 변경
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    links:
      - influxdb
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - k6-network

networks:
  k6-network:
    driver: bridge
