server:
  servlet:
    context-path: /api

spring:
  application:
    name: reservation-app
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /docs/openapi3.yaml

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  otlp:
    tracing:
      endpoint: ${TEMPO_ENDPOINT} # Tempo의 HTTP 수신 포트
  tracing:
    sampling:
      probability: 0.1

jwt:
  secret-key: ${JWT_SECRET_KEY}

portone.secret:
  storeId: ${PORTONE_API_STOREID}
  apiSecret: ${PORTONE_API_SECRET}
  webhookSecret: ${PORTONE_WEBHOOK_SECRET}

loki:
  endpoint: ${LOKI_URL}/loki/api/v1/push

jdbc:
  datasource-proxy:
    logging: slf4j
    multiline: false
    slow-query:
      enable-logging: true
      log-level: WARN
      logger-name: slow-query-logger
      threshold: 2 # 2초이상걸리면 slow
logging:
  level:
    slow-query-logger: WARN
