server:
  servlet:
    context-path: /api

spring:
  application:
    name: reservation-dev
  datasource:
    url: jdbc:mariadb://localhost:3306/movie_db
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /docs/openapi3.yaml

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1

jwt:
  secret-key: ${JWT_SECRET_KEY}

portone.secret:
  storeId: ${PORTONE_API_STOREID}
  apiSecret: ${PORTONE_API_SECRET}
  webhookSecret: ${PORTONE_WEBHOOK_SECRET}

loki:
  endpoint: http://localhost:3100/loki/api/v1/push

jdbc:
  datasource-proxy:
    include-parameter-values: true
    logging: slf4j
    multiline: true
    query:
      log-level: DEBUG
      logger-name: query-logger
      enable-logging: true
    slow-query:
      enable-logging: true
      log-level: WARN
      logger-name: slow-query-logger
      threshold: 2 # 2초이상걸리면 slow
logging:
  level:
    query-logger: DEBUG
    slow-query-logger: WARN
