server:
  servlet:
    context-path: /api

spring:
  application:
    name: reservation-app
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mariadb://localhost:3306/movie_db?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc.batch_size: 50
        order_inserts: true
  flyway:
    enabled: true
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /docs/openapi3.yaml

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
  otlp:
    tracing:
      endpoint: http://tempo-prod-20-prod-ap-northeast-0.grafana.net:443
      headers:
        Authorization: "Basic MTIwOTE2MzpnbGNfZXlKdklqb2lNVFF5T1RNeU5DSXNJbTRpT2lKeVpYTmxjblpoZEdsdmJpMTBkSFIwZEhSMElpd2lheUk2SWpCUGRUazNObE5yWVRnd1VsRllNemgxVW5VMU9FbFhieUlzSW0waU9uc2ljaUk2SW5WekluMTk="
      transport: http
  tracing:
    sampling:
      probability: 1
    # 2. 뒤에 포트 443을 붙이세요
jwt:
  secret-key: ${JWT_SECRET_KEY}

portone.secret:
  storeId: ${PORTONE_API_STOREID}
  apiSecret: ${PORTONE_API_SECRET}
  webhookSecret: ${PORTONE_WEBHOOK_SECRET}

jdbc:
  datasource-proxy:
    include-parameter-values: true
    logging: slf4j
    multiline: true
    query:
      log-level: DEBUG
      logger-name: query-logger
      enable-logging: true
    slow-query:
      enable-logging: true
      log-level: WARN
      logger-name: slow-query-logger
      threshold: 2 # 2초이상걸리면 slow
logging:
  level:
    query-logger: DEBUG
    slow-query-logger: WARN
    com.rejs.reservation: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      portOne:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallDurationThreshold: 3000
        recordExceptions:
          - java.lang.Throwable
          - io.portone.sdk.server.errors.UnknownException
        ignoreExceptions:
          - io.portone.sdk.server.errors.PortOneException