name: Backend CI/CD to Amazon ECR

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**" # backend 폴더 변화 시에만 작동

env:
  # 아래서 {{env}}로 사용가능
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: reservation-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ARM64 빌드를 위한 QEMU 설정
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Docker Buildx 설정 (멀티 아키텍처 빌드 도구)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Amazon ECR 로그인
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      # Docker 빌드 및 ECR 푸시
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/arm64 # t4g(Graviton)를 위해 ARM64 지정
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
